server:
  port: 3007

spring:
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/relatoriosdb}
    username: ${DB_USERNAME:user}
    password: ${DB_PASSWORD:pass}
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

# URLs dos outros serviços
services:
  auth:
    url: ${AUTH_SERVICE_URL:http://localhost:3001}
  eventos:
    url: ${EVENTOS_SERVICE_URL:http://localhost:3002}
  inscricoes:
    url: ${INSCRICOES_SERVICE_URL:http://localhost:3003}
  palestrantes:
    url: ${PALESTRANTES_SERVICE_URL:http://localhost:3004}
  certificados:
    url: ${CERTIFICADOS_SERVICE_URL:http://localhost:3005}
  avaliacoes:
    url: ${AVALIACOES_SERVICE_URL:http://localhost:3006}

logging:
  level:
    com.eventos.relatorios: DEBUG