server:
  port: 8080

spring:
  application:
    name: relatorios-service

  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/relatoriosdb}
    username: ${DB_USERNAME:relatorios_user}
    password: ${DB_PASSWORD:relatorios_pass}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  web:
    client:
      connection-timeout: 5000
      read-timeout: 10000
    cors:
      allowed-origins: "*"
      allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
      allowed-headers: "*"

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    com.eventos.relatorios: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics"
  endpoint:
    health:
      show-details: always

security:
  jwt:
    secret: ${JWT_SECRET:seu-secret-jwt-aqui}
    expiration: 86400000

services:
  eventos:
    url: ${SERVICES_EVENTOS_URL:http://localhost:8081}
  inscricoes:
    url: ${SERVICES_INSCRICOES_URL:http://localhost:8082}
  palestrantes:
    url: ${SERVICES_PALESTRANTES_URL:http://localhost:8083}
  certificados:
    url: ${SERVICES_CERTIFICADOS_URL:http://localhost:8084}
  avaliacoes:
    url: ${SERVICES_AVALIACOES_URL:http://localhost:8085}
