version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: relatorios-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: relatoriosdb
      MYSQL_USER: relatoriosuser
      MYSQL_PASSWORD: relatoriospass
    ports:
      - "3308:3308"
    volumes:
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
